version: 2

models:
  - name: users_stg
    description: "Formatted version of the users table. Users who have made orders on our website."
    columns:
      - name: id
        description: "The primary key for the greenery users table."
        tests:
          - unique
          - not_null

  - name: events_stg
    description: "Formatted version of the events table. Instances of people making orders on our website."
    columns:
      - name: event_id
        description: "The primary key for the greenery events table."
        tests:
          - unique
          - not_null

  - name: addresses_stg
    description: "Formatted version of the addresses table. Addresses where orders should be delivered to."
    columns:
      - name: address_id
        description: "The primary key for the greenery addresses table."
        tests:
          - unique
          - not_null

  - name: orders_stg
    description: "Formatted version of the orders table. Order details, including shipping information."
    columns:
      - name: order_id
        description: "The primary key for the greenery orders table."
        tests:
          - unique
          - not_null

  - name: products_stg
    description: "Formatted version of the products table. Product info including price and inventory."
    columns:
      - name: product_id
        description: "The primary key for the greenery productss table."
        tests:
          - unique
          - not_null

  - name: order_items_stg
    description: "Formatted version of the order_items table. Fact table connecting orders and products."
    columns:
      - name: order_id
        description: "The primary key for the greenery order_items table."
        tests:
          - unique
          - not_null

  - name: promos_stg
    description: "Formatted version of the promos table. Promotion details including whether the promo is still active."
    columns:
      - name: promo_id
        description: "The primary key for the greenery promos table."
        tests:
          - unique
          - not_null