version: 2

sources:
  - name: public
    description: A replica of the database from greenery
    tables:
      - name: addresses
      - name: events
      - name: order_items
      - name: orders
      - name: products
      - name: promos
      - name: superheroes
      - name: users