version: 2

on-run-end:
  - "grant usage on schema {{dbt_junji_s}} to role reporting"

models:
  - name: stg_greenery__users
    description: "Staging version of the users table. Users who have made orders on our website."
    columns:
      - name: user_guid
        description: "The primary key for users."
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: address_id
        description: "Joins to stg_greenery__addresses table." 
      - name: created_at_utc
        description: "Records are in UTC time zone."
      - name: updated_at_utc
        description: "Records are in UTC time zone."
      

  - name: stg_greenery__events
    description: "Staging version of the events table. Instances of people making orders on our website."
    columns:
      - name: event_guid
        description: "The primary key for events."
        tests:
          - unique
          - not_null
      - name: session_id
      - name: user_id 
        description: "Joins to stg_greenery__users table."
      - name: page_url
      - name: event_type
      - name: order_id
        description: "Joins to stg_greenery__orders table."
      - name: product_id
        description: "Joins to stg_greenery__products table."
      - name: created_at_utc
        description: "Records are in UTC time zone."


  - name: stg_greenery__addresses
    description: "Staging version of the addresses table. Addresses where orders should be delivered to."
    columns:
      - name: address_guid
        description: "The primary key for addresses."
        tests:
          - unique
          - not_null
      - name: street_address
      - name: zicode
      - name: state
      - name: country


  - name: stg_greenery_orders
    description: "Staging version of the orders table. Order details, including shipping information."
    columns:
      - name: order_guid
        description: "The primary key for orders."
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Joins to stg_greenery__users table."
      - name: promo_id
        description: "Joins to stg_greenery__promos table."
      - name: order_cost
      - name: shipping_cost
      - name: order_total_cost
      - name: address_id
        description: "Joins to stg_greenery__addresses table."
      - name: tracking_id
        tests:
          - unique
          - not_null
      - name: shipping_service
      - name: created_at_utc
        description: "Records are in UTC time zone."
      - name: estimated_delivery_utc
        description: "Records are in UTC time zone."
      - name: delivered_at_utc
        description: "Records are in UTC time zone."
      - name: delivery_status
      

  - name: stg_greenery__products
    description: "Staging version of the products table. Product info including price and inventory."
    columns:
      - name: product_guid
        description: "The primary key for products."
        tests:
          - unique
          - not_null
      - name: product_name
      - name: product_price
      - name: product_inventory


  - name: stg_greenery__order_items
    description: "Staging version of the order_items table. Fact table connecting orders and products purchased."
    columns:
      - name: order_id
        description: "Joins to stg_greenery__orders table."
      - name: product_id
        description: "Joins to stg_greenery__products table."
      - name: quantity
        

  - name: stg_greenery__promos
    description: "Staging version of the promos table. Promotion details including whether the promo is still active."
    columns:
      - name: promo_guid
        description: "The primary key for promotions."
        tests:
          - unique
          - not_null
      - name: promo_discount
      - name: promo_status
        tests: 
          - accepted_values:
              values: ["active", "inactive"]
  

  - name: dim_greenery__user_order_summary
    columns:
      - name: user_guid
        tests:
          - unique
          - not_null
      - name: count_orders
        description: "For each unique user, count the number of orders they've made at any time."
      - name: count_products_purchased
        description: "For each unique user, count the number of products they've purchased at any time."
      - name: count_promos_used
        description: "For each unique user, count the number of promotions they've used at any time."
      - name: total_money_spent
        description: "For each unique user, sum the total amount of spent at any time."
      - name: money_saved_with_promos
        description: "For each unique user, sum the amount of money saved through promotions."
      - name: avg_delivery_time
        description: "For each unique user, across all deliveries return the average delivery time."

  - name: fct_greenery__promo_orders
    columns:
    - name: promo_guid
      tests:
        - unique
        - not_null
    - name: count_orders_applied
      description: "For each promotion, count the number of orders it has been applied on at any time."
    - name: count_users_applied
      description: "For each promotion, count the number of users who have applied it at any time."
    - name: total_discounts_from_promos
      description: "For each promotion, sum the amount of money discounted from it at any time."
    - name: date_promo_first_applied_utc
    - name: date_promo_last_applied_utc
    - name: current_promo_status
      tests: 
        - accepted_values:
            values: ["active", "inactive"]

  - name: dim_greenery__user_addresses
    columns:
    - name: state
    - name: country
    - name: count_users
      description: "Per state and country, count the number of unique users at any time."
    - name: count_orders
      description: "Per state and country, count the number of unique orders made at any time."

  - name: dim_greenery__sessions_summary
    columns:
      - name: session_id
        tests:
          - unique
          - not_null
      - name: user_id
      - name: count_pages_visited
        description: "Per session on our website, count the number of pages visited."
      - name: count_events
        description: "Per session on our website, count the number of events."
      - name: order_made
        description: "Per session on our website, flag whether an order was made or not." 
        tests: 
        - accepted_values:
            values: ["1"]
      - name: count_unique_products_viewed
      - name: count_unique_products_ordered
      - name: count_number_of_products_ordered
      - name: time_first_page_opened_utc
        description: "Per session on our website, return the time when the first page was opened."
      - name: time_spent_during_session
        description: "Per session on our website, return the amount of time spend on our website in total."

  - name: fct_greenery__page_views
    description: "This model shows how many views our web pages are getting during each week of the year."
    columns:
      - name: page_url
        tests:
            - unique
            - not_null
      - name: year
      - name: week
      - name: count_views

  - name: dim_greenery__user_summary
    columns:
      - name: user_guid
        tests:
            - unique
            - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: address_id
      - name: created_at_utc
      - name: updated_at_utc
      - name: count_sessions
      - name: count_orders
      - name: count_products_purchased

  - name: fct_greenery__sessions_orders
    columns:
      - name: session_id
      - name: user_id
      - name: page_url
      - name: event_guid
      - name: viewed_product_id
        description: "ID of products that a user views on our web page."
      - name: viewed_product_name
      - name: order_id
      - name: ordered_product_id
        description: "ID of products that a user has ordered."
      - name: ordered_product_name
      - name: quantity
      - name: created_at_utc

  - name: fct_greenery__orders_summary
    columns:
      - name: order_guid
        tests:
            - unique
            - not_null
      - name: user_id
      - name: order_cost
      - name: shipping_cost
      - name: order_total_cost
      - name: promo_id
      - name: promotion_amount_applied
      - name: count_unique_products_purchased
      - name: count_items_purchased
      - name: address_id
      - name: tracking_id
      - name: shipping_service
      - name: created_at_utc
      - name: estimated_delivery_utc
      - name: delivered_at_utc
      - name: delivery_status

  - name: fct_greenery__orders_status

  - name: dim_greenery__shipping_service_performance